### ISSUE TITLE
EagerLoading: Issue with generated stubs

### ISSUE THREAD

**Issue by jmortlock** [bigcommerce/gruf-demo#32]
Hi

If you are eager loading Zeitwerk will complain about the classes that get generated.

```
/home/mortlock/src/gruf-demo/vendor/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get': uninitialized constant App::Proto::ProductsPb (NameError)

    parent.const_get(cname, false)
          ^^^^^^^^^^
```

To reproduce
```
RAILS_ENV=production bundle exec gruf
```
Or you can set eager_loading to true in test mode and run the suite, modern rails actually use this in test.rb
```
  # Eager loading loads your whole application. When running a single test locally,
  # this probably isn't necessary. It's a good idea to do in a continuous integration
  # system, or in some way before deploying your code.
  config.eager_load = ENV["CI"].present?
```

The workaround is to generate the stubs into a non rails directory, I have chosen lib.
Happy to open a PR if you see this as acceptable solution.

**Comment by splittingred** [comment]
Fixed, thanks for reporting this!

**Comment by jtippett** [comment]
Apologies for reviving this somewhat dead thread, but these issues remain, especially since the `generate.sh` shell script was not updated to match the new layout. The current structure works until someone tries to regenerate the stubs, then it will fail again.

But I think that the real solution is not further hacks but perhaps to place much more emphasis on the much, much better solution, which is to simply place the protos and their generated artifacts in a gem and go from there. I spent hours fruitlessly banging my head against confusing, arcane errors before finally giving up and going the gem route - which took something like 20 minutes literally from start to finish. It's the only way to go. Generated files and rails/zeitwerk naming conventions/restrictions simply do not mix and trying to force them to is a waste of time.

For anyone frustrated and looking through these issues for help, I found this article helpful: https://medium.com/@shiladitya16/building-micro-services-using-grpc-on-ruby-41acb755ee06

It's a waste of time trying to make these files work *anywhere* in Rails.
